<?php require('template/header.phtml');

?>


<body>
<?php echo "
<form action='' method='post'>
    <div class='form-group'>
        <label for='username'>Email address</label>
        <input type='email' class='form-control' name='username' id='username' required='required'
               placeholder='name@example.com'>
    </div>

    <div class='form-group'>
        <label for='realname'>Full Name</label>
        <input class='form-control' name='realname' id='realname' required='required' placeholder='John Smith'>
    </div>

    <div class='form-group'>
        <label for='password'>Password</label>
        <input class='form-control' name='password' id='password' required='required' placeholder='Example - Q2wdft4f'>
    </div>

    <div class='form-group'>
        <label for='profile_photo'>Profile Image URL</label>
        <input class='form-control' name='profile_photo' id='profile_photo' placeholder='Paste URL here'>
    </div>

    <div class='form-group'>
        <label for='phone_number'>Contact Number</label>
        <input class='form-control' name='phone_number' id='phone_number' required='required' placeholder='01612345678'>
    </div>

    <button class='btn btn-outline-danger' type='submit' name='register' href='index.php'>Register</button>

</form>
<br>
<br>
<br>
<br>
"; ?>
</body>
