<?php
// Include the index.php file
require_once('index.php');
// Include the User.php file located in the Models directory
require_once('Models/User.php');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap core CSS -->

    <!-- Link to a Bootstrap CSS file hosted on a CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <!-- Link to a custom CSS file -->
    <link href="/css/my-style.css" rel="stylesheet">





    <!-- Add the Bootstrap JavaScript file -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
            integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
            crossorigin="anonymous"></script>

    <!--<script src="https://cdn.jsdelivr.net/npm/ol@latest/dist/ol.js"></script>-->





    <?php echo $view->location;

    ?>



</head>




<!--<body role=""document"> -->


<header>
    <!-- Fixed navbar -->

    <!-- Navbar with a dark background color -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <!-- Container element to center the navbar content -->
        <div class="container-fluid">
            <!-- Navbar brand -->
            <a class="navbar-brand" href="#"></a>
            <!-- Navbar toggler button -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <!-- Navbar toggler icon -->
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- Navbar content -->
            <div class="collapse navbar-collapse" id="navbarCollapse">

                <!-- Navbar links -->
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <?php

                    // Check if the user is logged in
                    if (!isset($_SESSION["login"])) {
                        // If the user is not logged in, display a login form
                        echo ' 
            <form method="post" action="" class="d-flex" >
                
                <input type="text" name="username" class="form-control me-2" placeholder="Username">
                
                <input type="password" name="password" class="form-control me-2" placeholder="Password">
                
                <button class="btn btn-outline-danger" type="submit" name="loginbutton">Login</button>
                
           </form>';
                    } else {
                        // If the user is logged in, display their name and a logout button
                        echo '
                            <li class="navbar-link">
                            
                            <a class="nav-link" href="index.php"><img src=' . '"' . $_SESSION['pic'] . '" class="img-thumbnail" width="50">  Welcome -    ' . $_SESSION['name'] . ' </a>
                            
                            </li>
                            <li class="nav-link"><form method="post" action="" class="form text-primary">
                            
                                <button class="btn btn-outline-danger" type="submit" name="logoutbutton">Logout</button>
                                 
                                       </form></li>
                            </li>
                            <li class="navbar-link">
                           
 
                            </li>
                    </ul>
                    </div>
        </div>
                    

                    <!-- Search form -->
                    <!--<form method="post" action="" class="d-flex">
                    
                        &lt;!&ndash; Dropdown menu to select the search criteria &ndash;&gt;
                        <select id="searchBy" name="searchBy" class="form-control me-2">
                            <option value="">Choose</option>
                            <option value="charge_points.postcode">Postcode</option>
                            <option value="charge_points.cost">Price</option>
                        </select>
                        &lt;!&ndash; Search input field &ndash;&gt;
                        <input type="text" name="searchPostcode" class="form-control me-2" placeholder="Search">
                        &lt;!&ndash; Submit button &ndash;&gt;
                        <button class="btn btn-outline-danger" type="submit" name="search">Search</button>
                    </form>-->
                    
                    

                    
                    ';
                    }
                    ?>

    </nav>
</header>

<body class="d-flex flex-column h-100">
<!-- Begin page content -->
<main class="flex-shrink-0">
    <br>
    <br>

    <div class="container">
        <div class="row">
            <div id="title" class="col-xs-12">



                <title><?php echo $view->pageTitle; ?></title>


                <!-- https://getbootstrap.com/docs/5.2/examples/sticky-footer-navbar/ -->

            </div>
        </div>

        <div class="row">
            <section id="content" class="col-xs-6 col-sm-9 col-md-10">
            </section>
        </div>

    </div>
</main>

</body>

